export const theme = {
    colors: {
        primary: '#91C5F2',
        primaryDeep: '#0069C3',
        primaryShadow: '#6D94B6',
        secondary: '#2ecc71',
        tertiary: '#80C67F',
        tertiaryDeep: '#147952',
        background: '#EBF0F4',
        gray: '#6C7377',
        yellow: '#ffd84e',
        orange: '#f7954f',
        lightOrange: '#F2C6A0',
        warn: '#FF3E3E',
        warnBackground: '#FFE5E5',
        inactive: '#CED1D3',
        bubble: '#EBF4F0',
        billBack: '#FEF9E6',
        billBlueBack: '#D9F3E3',
        billRedBack: '#FDE8CD',
        billBlueText: '#20A3CD',
        billRedText: '#FA8271',
    },
};
