spring:
  profiles:
    active: ${PROFILE}

  application:
    name: backend
  config:
    import: optional:file:.env[.properties]
  web:
    resources:
      add-mappings: false




--- # 로컬 설정
spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:zzfDB
    username: sa

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true


logging:
  level:
    root: info

--- # 개발 서버 설정
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: ${RDB_DRIVER}
    url: ${RDB_URL}
    username: ${RDB_USERNAME}
    password: ${RDB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none


logging:
  level:
    root: warn